name: Backend smoke tests


on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install backend dependencies
        working-directory: ./backend
        run: |
          npm ci
      - name: Run DB connection test (when MONGODB_URI provided as env)
        working-directory: ./backend
        # NOTE: Do not embed repository secrets directly in workflow YAML. To enable this test,
        # add a repository secret named MONGODB_URI and expose it in the workflow through
        # environment configuration in your CI settings or via a separate guarded step.
        run: |
          if [ -z "$MONGODB_URI" ]; then
            echo "MONGODB_URI not provided in environment, skipping DB connection test.";
          else
            echo "Running DB connection test...";
            node -e "const mongoose = require('mongoose'); mongoose.connect(process.env.MONGODB_URI).then(() => { console.log('DB connection successful'); process.exit(0); }).catch(err => { console.error('DB connection failed', err); process.exit(1); });"
          fi